name: landuse-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8   # 如果是CPU-only，请删掉这一行
  - numpy=1.24.3
  - pandas=2.0.3
  - matplotlib=3.7.2
  - scikit-learn=1.3.0
  - rasterio=1.3.8
  - geopandas=0.14.0
  - shapely=2.0.1
  - fiona=1.9.4
  - pyproj=3.6.0
  - requests=2.31.0
  - tqdm=4.65.0
  - ipykernel
  - pip
  - pip:
      - earthengine-api==0.1.358  # 如果需要用 Google Earth Engine
